---
- hosts: localhost
  gather_facts: False
  tasks:

  #Stopping container
    - name: Stop the docker container, local-ai
      docker_container:
        name: localai
        state: stopped

  #Removing/Deleting container
    - name: Remove container, local-ai
      docker_container:
        name: localai
        state: absent

  #Removing/Deleting Image
    - name: Remove image, local-ai
      docker_image:
        name: quay.io/go-skynet/local-ai:master-cublas-cuda12
        state: absent

  #Pull latest version Image
    - name: pull an image, local-ai
      docker_image:
        name: quay.io/go-skynet/local-ai:master-cublas-cuda12
        source: pull

  #deploy compose file
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: ~/srv/localai/
        files:
        - docker-compose.yml
        recreate: always
