version: '3.6'

services:
  api:
    container_name: localai
    image: quay.io/go-skynet/local-ai:v1.21.0-cublas-cuda12-ffmpeg #master-cublas-cuda12 #v1.20.0-cublas-cuda12-ffmpeg
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
        - MODELS_PATH=/models
        - BUILD_TYPE=cublas
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
        - DEBUG=true
    volumes:
        - ./models:/models:cached
        - ./pictures/:/tmp/
    command: ["/usr/bin/local-ai"]
    networks:
      - web-secure

  redis:
    image: redis:6.2.6
    container_name: redis.localai
    command: "redis-server --requirepass ${REDIS_HOST_PASSWORD}"
    volumes:
      - ./redis:/data
    networks:
      - web-secure
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379

  flowise:
    container_name: localai.flowise
    image: flowiseai/flowise:latest
    restart: always
    ports:
        - 3000:3000
    environment:
      - EXECUTION_MODE=main
      - DEBUG=false
      - LOG_PATH=./logs
    volumes:
        - ~/.flowise:/root/.flowise
        - ./logs/:/logs/
    command: /bin/sh -c "sleep 3; flowise start"
    networks:
      - web-secure

networks:
  web-secure:
    external: true