version: '3.6'

services:
  api:
    container_name: local-ai
    image: quay.io/go-skynet/local-ai:v0.19.0-cublas-cuda12
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
        - MODELS_PATH=/models
        - 'PRELOAD_MODELS=[{"url": "github:go-skynet/model-gallery/vicuna.yaml","name":"vicuna", "overrides": { "f16":true, "gpu_layers": 200, "mmap": true, "batch": 700 } } ]'        
        - BUILD_TYPE=cublas
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
        - ./models:/models:cached
        - ./pictures/:/tmp/
    command: ["/usr/bin/local-ai"]

  flowise:
    container_name: flowise-ai
    image: flowiseai/flowise:latest
    restart: always
    ports:
        - 3000:3000
    environment:
      - EXECUTION_MODE=child
      - DEBUG=true
      - LOG_PATH=./logs
    volumes:
        - ~/.flowise:/root/.flowise
        - ./logs/:/logs/
    command: /bin/sh -c "sleep 3; flowise start"