version: '3.6'

services:
  api:
    container_name: localai
    hostname: localai
    image: quay.io/go-skynet/local-ai:v1.23.2-cublas-cuda12
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai"]
    environment:
      - MODELS_PATH=/models
      - BUILD_TYPE=cublas
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DEBUG=true

  flowise:
    container_name: localai.flowise
    hostname: localai.flowise
    image: flowiseai/flowise:latest
    restart: always
    ports:
        - 3000:3000
    environment:
      - EXECUTION_MODE=main
      - DEBUG=true
      - LOG_PATH=./logs
    volumes:
        - ~/.flowise:/root/.flowise
        - ./logs/:/logs/
    command: /bin/sh -c "sleep 3; flowise start"

  redis:
    image: redis:6.2.6
    hostname: localai.redis
    container_name: localai.redis
    command: "redis-server --requirepass false"
    volumes:
      - ./redis:/data
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
